/**
 * This file was generated by Nexus Schema
 * Do not make changes to this file directly
 */


import type { Context } from "./src/context"




declare global {
  interface NexusGen extends NexusGenTypes {}
}

export interface NexusGenInputs {
}

export interface NexusGenEnums {
}

export interface NexusGenScalars {
  String: string
  Int: number
  Float: number
  Boolean: boolean
  ID: string
}

export interface NexusGenObjects {
  Course: { // root type
    courseTitle: string; // String!
    description?: string | null; // String
    id: string; // String!
    image?: string | null; // String
    price?: number | null; // Float
  }
  Lesson: { // root type
    description?: string | null; // String
    id: string; // String!
    title?: string | null; // String
    video?: string | null; // String
  }
  Query: {};
  Section: { // root type
    description?: string | null; // String
    id: string; // String!
    title?: string | null; // String
  }
}

export interface NexusGenInterfaces {
}

export interface NexusGenUnions {
}

export type NexusGenRootTypes = NexusGenObjects

export type NexusGenAllTypes = NexusGenRootTypes & NexusGenScalars

export interface NexusGenFieldTypes {
  Course: { // field return type
    courseTitle: string; // String!
    description: string | null; // String
    id: string; // String!
    image: string | null; // String
    price: number | null; // Float
    sections: Array<NexusGenRootTypes['Section'] | null>; // [Section]!
  }
  Lesson: { // field return type
    description: string | null; // String
    id: string; // String!
    title: string | null; // String
    video: string | null; // String
  }
  Query: { // field return type
    GetCourses: Array<NexusGenRootTypes['Course'] | null>; // [Course]!
    GetSingleCourse: NexusGenRootTypes['Course']; // Course!
  }
  Section: { // field return type
    description: string | null; // String
    id: string; // String!
    lessons: Array<NexusGenRootTypes['Lesson'] | null>; // [Lesson]!
    title: string | null; // String
  }
}

export interface NexusGenFieldTypeNames {
  Course: { // field return type name
    courseTitle: 'String'
    description: 'String'
    id: 'String'
    image: 'String'
    price: 'Float'
    sections: 'Section'
  }
  Lesson: { // field return type name
    description: 'String'
    id: 'String'
    title: 'String'
    video: 'String'
  }
  Query: { // field return type name
    GetCourses: 'Course'
    GetSingleCourse: 'Course'
  }
  Section: { // field return type name
    description: 'String'
    id: 'String'
    lessons: 'Lesson'
    title: 'String'
  }
}

export interface NexusGenArgTypes {
  Query: {
    GetSingleCourse: { // args
      id: string; // String!
    }
  }
}

export interface NexusGenAbstractTypeMembers {
}

export interface NexusGenTypeInterfaces {
}

export type NexusGenObjectNames = keyof NexusGenObjects;

export type NexusGenInputNames = never;

export type NexusGenEnumNames = never;

export type NexusGenInterfaceNames = never;

export type NexusGenScalarNames = keyof NexusGenScalars;

export type NexusGenUnionNames = never;

export type NexusGenObjectsUsingAbstractStrategyIsTypeOf = never;

export type NexusGenAbstractsUsingStrategyResolveType = never;

export type NexusGenFeaturesConfig = {
  abstractTypeStrategies: {
    isTypeOf: false
    resolveType: true
    __typename: false
  }
}

export interface NexusGenTypes {
  context: Context;
  inputTypes: NexusGenInputs;
  rootTypes: NexusGenRootTypes;
  inputTypeShapes: NexusGenInputs & NexusGenEnums & NexusGenScalars;
  argTypes: NexusGenArgTypes;
  fieldTypes: NexusGenFieldTypes;
  fieldTypeNames: NexusGenFieldTypeNames;
  allTypes: NexusGenAllTypes;
  typeInterfaces: NexusGenTypeInterfaces;
  objectNames: NexusGenObjectNames;
  inputNames: NexusGenInputNames;
  enumNames: NexusGenEnumNames;
  interfaceNames: NexusGenInterfaceNames;
  scalarNames: NexusGenScalarNames;
  unionNames: NexusGenUnionNames;
  allInputTypes: NexusGenTypes['inputNames'] | NexusGenTypes['enumNames'] | NexusGenTypes['scalarNames'];
  allOutputTypes: NexusGenTypes['objectNames'] | NexusGenTypes['enumNames'] | NexusGenTypes['unionNames'] | NexusGenTypes['interfaceNames'] | NexusGenTypes['scalarNames'];
  allNamedTypes: NexusGenTypes['allInputTypes'] | NexusGenTypes['allOutputTypes']
  abstractTypes: NexusGenTypes['interfaceNames'] | NexusGenTypes['unionNames'];
  abstractTypeMembers: NexusGenAbstractTypeMembers;
  objectsUsingAbstractStrategyIsTypeOf: NexusGenObjectsUsingAbstractStrategyIsTypeOf;
  abstractsUsingStrategyResolveType: NexusGenAbstractsUsingStrategyResolveType;
  features: NexusGenFeaturesConfig;
}


declare global {
  interface NexusGenPluginTypeConfig<TypeName extends string> {
  }
  interface NexusGenPluginInputTypeConfig<TypeName extends string> {
  }
  interface NexusGenPluginFieldConfig<TypeName extends string, FieldName extends string> {
  }
  interface NexusGenPluginInputFieldConfig<TypeName extends string, FieldName extends string> {
  }
  interface NexusGenPluginSchemaConfig {
  }
  interface NexusGenPluginArgConfig {
  }
}